@echo off
rem product-studio:windows-wrapper - generated by the pipeline from start.sh; do not edit.
rem start.sh is the launcher the pipeline actually ran and tested. This file
rem only runs it under Git Bash, so Windows gets the same startup. Change
rem start.sh instead: any edit here is replaced the next time the pipeline runs.
setlocal
cd /d "%~dp0"
if not exist "start.sh" goto :no_script

set "BASH_EXE="
if exist "%ProgramFiles%\Git\bin\bash.exe" set "BASH_EXE=%ProgramFiles%\Git\bin\bash.exe"
if not defined BASH_EXE if exist "%ProgramW6432%\Git\bin\bash.exe" set "BASH_EXE=%ProgramW6432%\Git\bin\bash.exe"
if not defined BASH_EXE if exist "%ProgramFiles(x86)%\Git\bin\bash.exe" set "BASH_EXE=%ProgramFiles(x86)%\Git\bin\bash.exe"
if not defined BASH_EXE if exist "%LocalAppData%\Programs\Git\bin\bash.exe" set "BASH_EXE=%LocalAppData%\Programs\Git\bin\bash.exe"
if not defined BASH_EXE if exist "%USERPROFILE%\scoop\apps\git\current\bin\bash.exe" set "BASH_EXE=%USERPROFILE%\scoop\apps\git\current\bin\bash.exe"
if not defined BASH_EXE for /f "delims=" %%G in ('where git.exe 2^>nul') do if not defined BASH_EXE if exist "%%~dpG..\bin\bash.exe" set "BASH_EXE=%%~dpG..\bin\bash.exe"
if not defined BASH_EXE goto :no_bash

"%BASH_EXE%" ./start.sh %*
exit /b %errorlevel%

:no_script
echo ERROR: start.sh was not found next to %~nx0.
exit /b 1

:no_bash
echo ERROR: Git Bash was not found. This project starts through start.sh on every platform.
echo Install Git for Windows from https://git-scm.com/download/win and run %~nx0 again.
exit /b 1
