// AUTO-GENERATED BY THE PIPELINE. Do not edit or delete.
//
// Dynamically imports every page/route module found under this project's
// pages/routes/views/screens directories. `npm run build` would also catch a
// broken import here, but that depends on whoever reads the build log
// recognising a resolution failure as a bug to fix. This test makes the same
// failure a real, unmissable vitest result instead: if an import below cannot
// resolve, THIS test fails, and vitest.xml records it as a failure the pipeline's
// fix loop is required to act on.
//
// If a test below fails: fix the import in the SOURCE file, not this test.
import { describe, it, expect } from 'vitest';


describe('pipeline: route modules resolve', () => {
  it('resolves app/providers.tsx', async () => {
    const mod = await import('../app/providers');
    expect(mod).toBeDefined();
  });
  it('resolves app/router.tsx', async () => {
    const mod = await import('../app/router');
    expect(mod).toBeDefined();
  });
  it('resolves pages/BacklogPage.tsx', async () => {
    const mod = await import('../pages/BacklogPage');
    expect(mod).toBeDefined();
  });
  it('resolves pages/OnboardingPage.tsx', async () => {
    const mod = await import('../pages/OnboardingPage');
    expect(mod).toBeDefined();
  });
  it('resolves pages/ReadinessPage.tsx', async () => {
    const mod = await import('../pages/ReadinessPage');
    expect(mod).toBeDefined();
  });
  it('resolves pages/ReviewPage.tsx', async () => {
    const mod = await import('../pages/ReviewPage');
    expect(mod).toBeDefined();
  });
  it('resolves pages/SavedWorkspacesPage.tsx', async () => {
    const mod = await import('../pages/SavedWorkspacesPage');
    expect(mod).toBeDefined();
  });
  it('resolves pages/SettingsPage.tsx', async () => {
    const mod = await import('../pages/SettingsPage');
    expect(mod).toBeDefined();
  });
  it('resolves pages/SignInPage.tsx', async () => {
    const mod = await import('../pages/SignInPage');
    expect(mod).toBeDefined();
  });
  it('resolves pages/WorkspacePage.tsx', async () => {
    const mod = await import('../pages/WorkspacePage');
    expect(mod).toBeDefined();
  });
});
