# AUTO-GENERATED BY THE PIPELINE. Do not edit or delete.
#
# Attempts to import every non-test Python module found in this backend.
# This catches:
#   - packages listed in imports but missing from requirements.txt/pyproject.toml
#   - broken relative imports (e.g. `from .utils import foo` where utils.py is gone)
#   - syntax errors in modules that no existing test exercises
#
# Uses importlib.import_module() — it does NOT call any application code, so
# missing env vars, databases, or external services will not cause false failures.
# If a test below fails: fix the import in the SOURCE module, not this file.
# This file is regenerated on every pass.

import importlib
import pytest

_MODULES = [
    "api",
    "api.deps",
    "api.routes",
    "api.routes.auth",
    "api.routes.review",
    "api.routes.workspace",
    "config",
    "core",
    "core.config",
    "core.database",
    "core.errors",
    "core.logging",
    "core.security",
    "domain",
    "domain.readiness_rules",
    "domain.share_access",
    "domain.story_sorting",
    "main",
    "models",
    "models.acceptance_criterion",
    "models.review_note",
    "models.review_share",
    "models.story",
    "models.user",
    "models.workspace",
    "repositories",
    "repositories.review_repository",
    "repositories.story_repository",
    "repositories.user_repository",
    "repositories.workspace_repository",
    "routes",
    "schemas",
    "schemas.auth",
    "schemas.common",
    "schemas.readiness",
    "schemas.review",
    "schemas.story",
    "schemas.vision",
    "schemas.workspace",
    "seed",
    "services",
    "services.auth_service",
    "services.readiness_service",
    "services.review_service",
    "services.story_service",
    "services.vision_service",
    "services.workspace_service",
]


@pytest.mark.parametrize('module_name', _MODULES)
def test_module_imports(module_name):
    """Verify the module can be imported without error."""
    mod = importlib.import_module(module_name)
    assert mod is not None
